steps:
  - label: ":docker: Build and scan image"
    commands: 
      - WIZ_SECRET=$(buildkite-agent secret get WIZ_SECRET)
      - WIZ_API_ID=$(buildkite-agent secret get WIZ_API_ID)
      - FOO=$(buildkite-agent secret get foo)
      - echo $FOO
      - docker build -t "plugin-demo:${BUILDKITE_BUILD_NUMBER}" .
    plugins:
      - wiz#v1.3.1:
          scan-type: 'docker'
          image-address: "plugin-demo:${BUILDKITE_BUILD_NUMBER}"
          api-secret-env: WIZ_SECRET
  
  - wait

  - label: ":terraform: Terraform scan"
    commands:
      - WIZ_SECRET=$(buildkite-agent secret get WIZ_SECRET)
      - WIZ_API_ID=$(buildkite-agent secret get WIZ_API_ID)
      - echo "Scanning Terraform"
    plugins:
      - wiz#v1.3.1:
          scan-type: iac
          iac-type: terraform
          api-secret-env: WIZ_SECRET
          path: './main.tf'
          parameter-files: './variables.tf'
          

      
