steps:
  - label: ":docker: Build and scan image"
    command: docker build -t "plugin-demo:${BUILDKITE_BUILD_NUMBER}" --load .
    plugins:
      - wiz#v1.3.1:
          scan-type: 'docker'
          image-address: "plugin-demo:${BUILDKITE_BUILD_NUMBER}"
          api-secret-env: WIZ_SECRET
  
  - wait

  - label: ":terraform: Terraform scan"
    commands: echo "Scanning Terraform"
    plugins:
      - wiz#v1.3.1:
          scan-type: iac
          iac-type: terraform
          api-secret-env: WIZ_SECRET
          path: './main.tf'
          parameter-files: './variables.tf'
          

      
